### ISSUE TITLE
Outdated Version of Mac App Error

### ISSUE THREAD

**Issue by darkroastcreative** [macecchi/pebble-itunesify-remote#13]
I've downloaded the latest versions of the Mac app (directly from this repository) as well as the Pebble app (from the Pebble app store), and the Pebble app keeps throwing an error at me stating that the Mac app is outdated (preventing use of the app).

Running Mac app version 1.5.0 on macOS 10.11.5 on a Mid-2015 MacBook Pro, and Pebble app version 1.5.0 on Pebble OS 3.14 on the Pebble Time model.

**Comment by macecchi** [comment]
Hi @dfinkdd, thanks for reporting this. 
Are you running anything else on port 8080? That error is thrown when a route for iTunesify returns a 404 status code from the Mac.

And yes, I've made a bad decision of not changing the iTunesify port to a more unusual one in the beginning :/

**Comment by darkroastcreative** [comment]
On my machine, an instance of Apache server is running on port 8080 for local development work, which I imagine is causing the issue.

Is it possible to add an option to specify a custom port number for the application? That might be a good means of avoiding collisions with ports in use, particularly for developers.

**Comment by macecchi** [comment]
Definitely! I'll add that feature in the next days :)

**Comment by macecchi** [comment]
Hey @dfinkdd. Just to let you know I'm still working on this issue but it's taking longer because I'm rewriting the whole Mac app as a native app.

**Comment by darkroastcreative** [comment]
I appreciate the update, @macecchi. I'm looking forward to see what you've built!

**Comment by macecchi** [comment]
Although it's not final yet, you can install the beta here:
https://github.com/macecchi/pebble-itunesify-remote/releases/tag/v2.0

This does not have an option to change the port, but you won't need it, as not it uses WebSockets with a different port (31415, to be more specific).

Could you try updating it and give me your feedback? :)

**Comment by darkroastcreative** [comment]
Just downloaded and installed the beta build, and it's working exactly as expected!

Though this isn't related to this issue, is it possible to display album art on the watch? I could see that being a cool feature for an upcoming iteration. Other than that, keep up the good work! :)

**Comment by macecchi** [comment]
Yay! Thanks for testing it :)

It is a cool idea indeed! I'm not sure if it's feasible but I'll research it :D
