### ISSUE TITLE
Track Names

### ISSUE THREAD

**Issue by Hecaterus** [macecchi/pebble-itunesify-remote#4]
I know you said they were coming soon but I'm impatient! If you could make it so that longer track names scroll left that would be ace. Keep up the work!

**Comment by macecchi** [comment]
iTunesify Remote 1.4 with track names and Pebble Time Round support

Update your Watchapp and also the Mac app:
- Pebble App: https://apps.getpebble.com/applications/55b5bdfe5e07169f58000022
- Mac App: https://github.com/macecchi/pebble-itunesify-remote-osx/releases/

Please don’t forget to heart the app on the Pebble Appstore to support its development :)

**Comment by macecchi** [comment]
Feature added on 9c6a91de2d4cb15695be827dcde9eeccb0360842.
